/**
 * Dados de demonstração do PropectAI.
 *
 * TODOS OS DADOS SÃO FICTÍCIOS. Nomes de empresa inventados, telefones na
 * faixa 9000-XXXX e 3000-XXXX (não atribuída), e-mails em domínios que não
 * existem. Nenhum dado veio de coleta real.
 *
 * Os scores não são escritos aqui: cada lead é pontuado pelo motor real
 * (`computeScore`, em @propectai/types) durante o seed. Se os pesos mudarem,
 * a demonstração acompanha sozinha — e um score escrito à mão que discorda
 * do motor é pior do que nenhum dado.
 */

export interface SeedLead {
  name: string;
  category: string;
  websiteStatus: 'SEM_SITE' | 'SITE_PRECARIO' | 'SITE_PROPRIO';
  website: string | null;
  websiteHasHttps: boolean | null;
  phone: string;
  /** Celular brasileiro → WhatsApp provável. Fixo → desconhecido. */
  isMobile: boolean;
  email: string | null;
  reviewCount: number;
  reviewRating: number;
  hasOpenHours: boolean;
  neighborhood: string;
  city: string;
  stateUf: string;
  postalCode: string | null;
  stage: string;
}

/** Preferências do tenant demo — alimentam PRIORITY_NICHE e SERVED_REGION. */
export const SEED_PREFERENCES = {
  servicesSold: ['Sites', 'Tráfego pago', 'Social media'],
  targetNiches: [
    'Dentistas',
    'Clínicas de Estética',
    'Salões de Beleza',
    'Academias',
    'Restaurantes',
  ],
  targetRegions: ['São Paulo, SP', 'Guarulhos, SP'],
  preferredChannel: 'WhatsApp',
  monthlyGoal: '4 a 10',
};

export const SEED_STAGES = [
  { slug: 'novo', name: 'Novo', color: '#6B7A99' },
  { slug: 'contato-enviado', name: 'Contato Enviado', color: '#3B82F6' },
  { slug: 'respondeu', name: 'Respondeu', color: '#2F6BFF' },
  { slug: 'reuniao-agendada', name: 'Reunião Agendada', color: '#8B5CF6' },
  { slug: 'proposta-enviada', name: 'Proposta Enviada', color: '#F59E0B' },
  { slug: 'negociacao', name: 'Negociação', color: '#F97316' },
  { slug: 'fechado', name: 'Fechado', color: '#22C55E', isTerminal: true, isWon: true },
  { slug: 'perdido', name: 'Perdido', color: '#EF4444', isTerminal: true },
];

export const SEED_SEARCHES = [
  {
    key: 'dentistas-sp',
    niche: 'Dentistas',
    stateUf: 'SP',
    city: 'São Paulo',
    neighborhood: 'Vila Mariana',
    radiusKm: 10,
    requestedCount: 10,
    status: 'COMPLETED' as const,
    daysAgo: 12,
    durationMs: 84_000,
    duplicates: 0,
  },
  {
    key: 'estetica-sp',
    niche: 'Clínicas de Estética',
    stateUf: 'SP',
    city: 'São Paulo',
    neighborhood: 'Moema',
    radiusKm: 8,
    requestedCount: 10,
    status: 'COMPLETED' as const,
    daysAgo: 6,
    durationMs: 127_000,
    duplicates: 3,
  },
  {
    key: 'academias-guarulhos',
    niche: 'Academias',
    stateUf: 'SP',
    city: 'Guarulhos',
    neighborhood: 'Centro',
    radiusKm: 15,
    requestedCount: 10,
    status: 'FAILED' as const,
    daysAgo: 2,
    durationMs: 301_000,
    duplicates: 0,
  },
];

/**
 * 25 leads distribuídos nas quatro faixas de score.
 *
 * A distribuição alvo é 6 muito alta, 7 alta, 8 média e 4 baixa — obtida
 * pelos atributos abaixo, não por número fixo. O seed valida a distribuição
 * ao final e avisa se ela sair do esperado.
 */
export const SEED_LEADS: SeedLead[] = [
  // --- Faixa muito alta -----------------------------------------------------
  {
    name: 'Sorriso Vivo Odontologia',
    category: 'Dentista',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0001',
    isMobile: true,
    email: 'contato@sorrisovivo-demo.com.br',
    reviewCount: 7,
    reviewRating: 4.9,
    hasOpenHours: true,
    neighborhood: 'Vila Mariana',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '04101-000',
    stage: 'novo',
  },
  {
    name: 'Clínica Estética Aurora',
    category: 'Clínica de estética',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0002',
    isMobile: true,
    email: 'atendimento@esteticaaurora-demo.com.br',
    reviewCount: 23,
    reviewRating: 4.7,
    hasOpenHours: true,
    neighborhood: 'Moema',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '04077-000',
    stage: 'contato-enviado',
  },
  {
    name: 'Academia Corpo & Movimento',
    category: 'Academia',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0003',
    isMobile: true,
    email: 'contato@corpoemovimento-demo.com.br',
    reviewCount: 4,
    reviewRating: 3.9,
    hasOpenHours: true,
    neighborhood: 'Pinheiros',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '05422-000',
    stage: 'novo',
  },
  {
    name: 'Restaurante Sabor da Vila',
    category: 'Restaurante',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0004',
    isMobile: true,
    email: 'reservas@sabordavila-demo.com.br',
    reviewCount: 12,
    reviewRating: 4.6,
    hasOpenHours: true,
    neighborhood: 'Vila Madalena',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '05435-000',
    stage: 'respondeu',
  },
  {
    name: 'Salão Bela Face',
    category: 'Salão de beleza',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0005',
    isMobile: true,
    email: 'contato@belaface-demo.com.br',
    reviewCount: 6,
    reviewRating: 4.8,
    hasOpenHours: false,
    neighborhood: 'Tatuapé',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '03071-000',
    stage: 'novo',
  },
  {
    name: 'Studio Odonto Guarulhos',
    category: 'Dentista',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0006',
    isMobile: true,
    email: 'contato@studioodonto-demo.com.br',
    reviewCount: 9,
    reviewRating: 5.0,
    hasOpenHours: true,
    neighborhood: 'Centro',
    city: 'Guarulhos',
    stateUf: 'SP',
    postalCode: null,
    stage: 'reuniao-agendada',
  },

  // --- Faixa alta -----------------------------------------------------------
  {
    name: 'Clínica Odonto Center',
    category: 'Dentista',
    websiteStatus: 'SITE_PRECARIO',
    website: 'https://odontocenter-demo.wixsite.com/inicio',
    websiteHasHttps: true,
    phone: '(11) 90000-0007',
    isMobile: true,
    email: 'contato@odontocenter-demo.com.br',
    reviewCount: 8,
    reviewRating: 4.7,
    hasOpenHours: true,
    neighborhood: 'Santana',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '02013-000',
    stage: 'contato-enviado',
  },
  {
    name: 'Odontologia Sorriso Real',
    category: 'Dentista',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0008',
    isMobile: true,
    email: null,
    reviewCount: 20,
    reviewRating: 4.3,
    hasOpenHours: true,
    neighborhood: 'Ipiranga',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '04263-000',
    stage: 'novo',
  },
  {
    name: 'Restaurante Cantinho Mineiro',
    category: 'Restaurante',
    websiteStatus: 'SITE_PRECARIO',
    website: 'https://cantinhomineiro-demo.negocio.site',
    websiteHasHttps: true,
    phone: '(11) 90000-0009',
    isMobile: true,
    email: 'contato@cantinhomineiro-demo.com.br',
    reviewCount: 30,
    reviewRating: 4.4,
    hasOpenHours: true,
    neighborhood: 'Bela Vista',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '01310-000',
    stage: 'proposta-enviada',
  },
  {
    name: 'Estúdio Beleza Pura',
    category: 'Salão de beleza',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0010',
    isMobile: true,
    email: null,
    reviewCount: 45,
    reviewRating: 4.6,
    hasOpenHours: false,
    neighborhood: 'Perdizes',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '05014-000',
    stage: 'novo',
  },
  {
    name: 'Espaço Zen Estética',
    category: 'Clínica de estética',
    websiteStatus: 'SITE_PRECARIO',
    website: 'https://espacozen-demo.base44.app',
    websiteHasHttps: true,
    phone: '(11) 90000-0011',
    isMobile: true,
    email: null,
    reviewCount: 8,
    reviewRating: 4.7,
    hasOpenHours: true,
    neighborhood: 'Itaim Bibi',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '04532-000',
    stage: 'contato-enviado',
  },
  {
    name: 'Academia Força Total',
    category: 'Academia',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 3000-0012',
    isMobile: false,
    email: null,
    reviewCount: 15,
    reviewRating: 4.5,
    hasOpenHours: true,
    neighborhood: 'Lapa',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '05077-000',
    stage: 'novo',
  },
  {
    name: 'Barbearia Nova Era',
    category: 'Barbearia',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 90000-0013',
    isMobile: true,
    email: 'novaera.barbearia.demo@gmail.com',
    reviewCount: 3,
    reviewRating: 4.6,
    hasOpenHours: true,
    neighborhood: 'Brás',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '03007-000',
    stage: 'respondeu',
  },

  // --- Faixa média ----------------------------------------------------------
  {
    name: 'Pet Shop Amigo Fiel',
    category: 'Pet shop',
    websiteStatus: 'SITE_PRECARIO',
    website: 'https://amigofiel-demo.linktr.ee',
    websiteHasHttps: true,
    phone: '(11) 90000-0014',
    isMobile: true,
    email: 'contato@amigofiel-demo.com.br',
    reviewCount: 5,
    reviewRating: 4.9,
    hasOpenHours: true,
    neighborhood: 'Saúde',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '04141-000',
    stage: 'novo',
  },
  {
    name: 'Restaurante Bom Prato Express',
    category: 'Restaurante',
    websiteStatus: 'SITE_PROPRIO',
    website: 'https://bompratoexpress-demo.com.br',
    websiteHasHttps: true,
    phone: '(11) 90000-0015',
    isMobile: true,
    email: 'contato@bompratoexpress-demo.com.br',
    reviewCount: 8,
    reviewRating: 4.4,
    hasOpenHours: true,
    neighborhood: 'Consolação',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '01302-000',
    stage: 'contato-enviado',
  },
  {
    name: 'Academia Vida Ativa',
    category: 'Academia',
    websiteStatus: 'SITE_PROPRIO',
    website: 'http://vidaativa-demo.com.br',
    websiteHasHttps: false,
    phone: '(11) 3000-0017',
    isMobile: false,
    email: null,
    reviewCount: 40,
    reviewRating: 4.1,
    hasOpenHours: true,
    neighborhood: 'Butantã',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '05503-000',
    stage: 'novo',
  },
  {
    name: 'Oficina Mecânica Torque',
    category: 'Oficina mecânica',
    websiteStatus: 'SEM_SITE',
    website: null,
    websiteHasHttps: null,
    phone: '(11) 3000-0018',
    isMobile: false,
    email: null,
    reviewCount: 2,
    reviewRating: 3.5,
    hasOpenHours: false,
    neighborhood: 'Mooca',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '03104-000',
    stage: 'novo',
  },
  {
    name: 'Barbearia Corte Fino',
    category: 'Barbearia',
    websiteStatus: 'SITE_PRECARIO',
    website: 'https://instagram.com/cortefino.demo',
    websiteHasHttps: true,
    phone: '(11) 90000-0019',
    isMobile: true,
    email: null,
    reviewCount: 55,
    reviewRating: 4.7,
    hasOpenHours: true,
    neighborhood: 'Pinheiros',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '05422-100',
    stage: 'negociacao',
  },
  {
    name: 'Clínica Dental Ipiranga',
    category: 'Dentista',
    websiteStatus: 'SITE_PROPRIO',
    website: 'https://dentalipiranga-demo.com.br',
    websiteHasHttps: true,
    phone: '(11) 90000-0020',
    isMobile: true,
    email: null,
    reviewCount: 25,
    reviewRating: 4.5,
    hasOpenHours: true,
    neighborhood: 'Ipiranga',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '04263-100',
    stage: 'novo',
  },
  {
    name: 'Salão Glamour',
    category: 'Salão de beleza',
    websiteStatus: 'SITE_PROPRIO',
    website: 'https://salaoglamour-demo.com.br',
    websiteHasHttps: true,
    phone: '(11) 90000-0021',
    isMobile: true,
    email: null,
    reviewCount: 70,
    reviewRating: 4.8,
    hasOpenHours: true,
    neighborhood: 'Jardins',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '01402-000',
    stage: 'proposta-enviada',
  },
  {
    name: 'Estética Renove',
    category: 'Clínica de estética',
    websiteStatus: 'SITE_PROPRIO',
    website: 'https://esteticarenove-demo.com.br',
    websiteHasHttps: true,
    phone: '(11) 3000-0022',
    isMobile: false,
    email: null,
    reviewCount: 33,
    reviewRating: 4.4,
    hasOpenHours: true,
    neighborhood: 'Vila Olímpia',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '04547-000',
    stage: 'fechado',
  },

  // --- Faixa baixa ----------------------------------------------------------
  {
    name: 'Mega Fitness Center',
    category: 'Academia',
    websiteStatus: 'SITE_PROPRIO',
    website: 'https://megafitness-demo.com.br',
    websiteHasHttps: true,
    phone: '(11) 3000-0023',
    isMobile: false,
    email: null,
    reviewCount: 320,
    reviewRating: 4.9,
    hasOpenHours: true,
    neighborhood: 'Morumbi',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '05650-000',
    stage: 'perdido',
  },
  {
    name: 'Imobiliária Central Prime',
    category: 'Imobiliária',
    websiteStatus: 'SITE_PROPRIO',
    website: 'https://centralprime-demo.com.br',
    websiteHasHttps: true,
    phone: '(11) 90000-0024',
    isMobile: true,
    email: null,
    reviewCount: 150,
    reviewRating: 3.9,
    hasOpenHours: true,
    neighborhood: 'Higienópolis',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '01241-000',
    stage: 'novo',
  },
  {
    name: 'Advocacia Menezes',
    category: 'Escritório de advocacia',
    websiteStatus: 'SITE_PROPRIO',
    website: 'https://advmenezes-demo.com.br',
    websiteHasHttps: true,
    phone: '(11) 3000-0025',
    isMobile: false,
    email: null,
    reviewCount: 90,
    reviewRating: 4.3,
    hasOpenHours: true,
    neighborhood: 'Paulista',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '01310-100',
    stage: 'novo',
  },
  {
    name: 'Lanchonete Ponto Certo',
    category: 'Lanchonete',
    websiteStatus: 'SITE_PROPRIO',
    website: 'https://pontocerto-demo.com.br',
    websiteHasHttps: true,
    phone: '(11) 90000-0026',
    isMobile: true,
    email: null,
    reviewCount: 60,
    reviewRating: 2.4,
    hasOpenHours: true,
    neighborhood: 'Liberdade',
    city: 'São Paulo',
    stateUf: 'SP',
    postalCode: '01508-000',
    stage: 'novo',
  },
];
